name: (O11) Release Plugin

on:
  workflow_dispatch:
    inputs:
      tag: 
        description: 'The repo version tag'
        required: true
        type: string
      forgeVersion:
        description: 'The plugin version on the forge'
        required: true
        type: string
      mabsMin:
        description: 'Minimum MABS version'
        required: true
        type: string
      releaseNotes:
        description: 'Release Notes'
        required: true
        type: string

jobs:    
  change-extensibility:
    uses: ./.github/workflows/o11_change_extensibility.yml
    name: '✍🏻 Update OML Extensibility'
    secrets: inherit
    with:
      plugin: BarcodeAutomation
      configName: InAppBrowser Plugin
      tag: ${{ github.event.inputs.tag }}
      forgeVersion: ${{ github.event.inputs.forgeVersion }}
      mabsMin: ${{ github.event.inputs.mabsMin }}
      environment: enmobile11-dev.outsystemsenterprise.com

  deploy:
    name: '🔌 Deploy plugin across LifeTime'
    runs-on: ubuntu-latest
    needs: change-extensibility
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
    
    - name: Tag Plugin with Version 
      run: npm run update:version --plugin=BarcodeAutomation --lifetime=${{ secrets.LIFETIME}} --authentication='${{secrets.AUTOMATION_TOKEN}}'

    - name: Wait for tag version to propagate
      run: sleep 20  # Waits for 20 seconds

    - name: Deploying from DEV to TST
      run: npm run deploy --plugin=BarcodeAutomation --from=Development --to=Testing --lifetime=${{ secrets.LIFETIME }} --authentication='${{ secrets.AUTOMATION_TOKEN }}'

    - name: Wait for deployment to propagate
      run: sleep 20  # Waits for 20 seconds
    
    - name: Deploying from TST to PROD 
      run: npm run deploy --plugin=BarcodeAutomation --from=Testing --to=Production --lifetime=${{ secrets.LIFETIME }} --authentication='${{ secrets.AUTOMATION_TOKEN }}'
  
  release:
    uses: ./.github/workflows/o11_github_release.yml
    name: '🚀 Create Github release'
    secrets: inherit
    needs: deploy
    with:
      tag: ${{ github.event.inputs.tag }}
      environment: Production
      plugin: BarcodeAutomation
      notes: ${{ github.event.inputs.releaseNotes }}

