name: (O11) Download Plugin

on:
  workflow_call:  
    inputs:
      tag: 
        required: true
        type: string
      plugin: 
        description: 'Plugin'
        required: true
        type: string
      environment:
        description: 'The O11 environment we are downloading from'
        required: true
        type: string
      notes:
        description: 'The release notes'
        required: true
        type: string

jobs:    
  download:
    name: Download OAP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Download the OAP from LifeTime
      run: npm run download --plugin=${{inputs.plugin}} --environment=${{inputs.environment}} --lifetime=${{ secrets.LIFETIME }} --authentication='${{ secrets.AUTOMATION_TOKEN }}'
    
    - name: Upload as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugin
        path: ./downloads/release.oap
        retention-days: 5

    - name: Step 3 - Create GitHub Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ inputs.tag }} './downloads/release.oap#O11Asset'  -n ${{inputs.notes}} --latest=false 